const ENV_VARS = Object.freeze({
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  POSTGRES: {
    DB_PORT: 'DB_PORT',
    DB_DIALECT: 'DB_DIALECT',
    DB_USERNAME: 'DB_USERNAME',
    DB_PASSWORD: 'DB_PASSWORD',
    DB_DATABASE: 'DB_DATABASE',
    DB_HOST: 'DB_HOST',
  },
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  CLOUDINARY: {
    NAME: 'CLOUDINARY_NAME',
    API_KEY: 'CLOUDINARY_API_KEY',
    API_SECRET: 'CLOUDINARY_API_SECRET',
    ENABLE: 'ENABLE_CLOUDINARY',
  },
})

export default ENV_VARS;